#! /bin/bash

if [ ! -v DIRABUS ]; then DIRABUS=dirabus; fi
if [ ! -v ACEPTADOS ]; then ACEPTADOS=aceptados; fi

if [ ! -d $DIRABUS ]; then mkdir $DIRABUS; fi
if [ ! -d $ACEPTADOS ]; then mkdir $ACEPTADOS; fi

for (( i = 1; ; i++ )); do
    mv $DIRABUS/* $ACEPTADOS
    sleep 1
done
