#!/usr/bin/env bash



LOGFILE=preparador
LOGS='../test/testPreparador/dirconf'
source log.sh

function reportar() {
    echo $1
    log $1
}

declare -r ejecutables="ejecutables"
declare -r maestros="maestros"
declare -r aceptados="aceptados"
declare -r rechazados="rechazados"
declare -r validados="validados"
declare -r reportes="reportes"
declare -r logs="logs"

declare -A map

while read linea
do
    if [[ -z $linea ]]; then
      continue
    fi
    key=$(reportar "$linea" | grep --only-matching '^[^-]*')

    map[$key]=$((${map[$key]} + 1))

done < '../test/testPreparador/config.config'

declare -A mapErrors

#nombrar directorios faltantes, cortar ejecucion
  if [[ -z "${map[${ejecutables}]}" ]]; then
    reportar "No existe el directorio $ejecutables"
  fi
  if [[ -z "${map[${maestros}]}" ]]; then
    reportar "No existe el directorio $maestros";
  fi
  if [[ -z "${map[${aceptados}]}" ]]; then
    reportar "No existe el directorio $aceptados";
  fi
  if [[ -z "${map[${rechazados}]}" ]]; then
    reportar "No existe el directorio $rechazados";
  fi
  if [[ -z "${map[${validados}]}" ]]; then
    reportar "No existe el directorio $validados";
  fi
  if [[ -z "${map[${reportes}]}" ]]; then
    reportar "No existe el directorio $reportes";
  fi
  if [[ -z "${map[${logs}]}" ]]; then
    reportar "No existe el directorio $logs";
  fi


for i in "${!map[@]}"
do
  case $i in

    $ejecutables )
      ;;
    $maestros )
      ;;
    $aceptados )
      ;;
    $rechazados )
    ;;
    $validados )
    ;;
    $reportes )
    ;;
    $logs )
    ;;
    * ) mapErrors[$i]="Directorio $i inválido, verifique las rutas de configuración"
        continue
   ;;
  esac

  if [[ ${map[$i]} -gt 1 ]]; then
    mapErrors[$i]="Directorio $i esta duplicado"
  fi

done

for i in "${!mapErrors[@]}"
do
  reportar "${mapErrors[$i]}"
done
