#! /bin/bash

# -C find processes with specified command
# -o "pid=" print only the process id, without headers
if [ "$(ps -C "demonio" -o "pid=")" != "" ]; then exit; fi
nohup 2>/dev/null ./demonio >/dev/null &
